config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :projects do
    resources :user_stories
  end

  authenticated :user do
    root 'projects#index', as: 'authenticated_user'
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :user_stories, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
end

app/models/user_story.rb
class UserStory < ApplicationRecord
  belongs_to :project
  validates :priority, numericality: { only_integer: true, :greater_than_or_equal_to => 1, :less_than_or_equal_to => 10, message: " must be a number from 1 to 10"  }, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:edit, :show, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  def index
    @projects = Project.where(user_id: current_user)
  end

  def new
    @project = current_user.projects.new
  end

  def create
    @project = current_user.projects.new(project_params)

    if @project.save
      redirect_to @project, notice: "Project created."
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: "Congratulation! Project modified."
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def find_project
    @project = Project.find(params[:id])
  end

end

app/controllers/user_stories_controller.rb
class UserStoriesController < ApplicationController
  before_action :find_project, only: [:index, :new, :create]
  before_action :find_user_story, only: [:show, :edit, :update, :destroy]

  def index
    @user_stories = @project.user_stories.all
  end

  def show
  end

  def new
    @user_story = @project.user_stories.new
  end

  def create
    @user_story = @project.user_stories.create(user_story_params)

    if @user_story.save
      redirect_to project_user_story_path(@project, @user_story), notice: "User story created."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user_story.update(user_story_params)
      redirect_to project_user_story_path(@project, @user_story), notice: "User story modified."
    else
      render 'edit'
    end
  end

  def destroy
    @user_story.destroy
    redirect_to project_path(@project)
  end

  private

  def user_story_params
    params.require(:user_story).permit(:actor, :goal, :reason, :criteria, :priority)
  end

  def find_project
    @project = Project.find(params[:project_id])
  end

  def find_user_story
    find_project
    @user_story = @project.user_stories.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user_stories_helper.rb
module UserStoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="alerts">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p> 
    </div>

    <nav id="main-nav">
      <div id="logo"><p><%= link_to "UrStry", root_path %></p></div>
      <ul>
        <% if user_signed_in? %>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete%></li>
        <% else %>
          <li><%= link_to "Register", new_user_registration_path%></li>
          <li><%= link_to "Log In", new_user_session_path%></li>
        <% end %>
      </ul>
    </nav>

    <div id=content>
      <%= yield %>
    </div>
    
    <footer id="main-footer">
      <p> Contact </p>
    </footer>
  </body>

</html>

app/views/projects/edit.html.erb
<h1>Edit Project - <%= @project.name%></h1>

<%= @project.errors.full_messages.first if @project.errors.any? %>

<%= form_for @project, url: {action: "update"} do |f| %>
  <%= label_tag "Name" %>
  <%= f.text_field :name %>
  </br></br></br>
  <%= label_tag "Description" %>
  <%= f.text_area :description, size: "60x12" %>
  </br></br></br>
  <%= f.submit "Update" %>
<% end %>

<p><%= link_to "Cancel", @project %></p>

app/views/projects/index.html.erb
<h1>PROJECTS </h1>
<br>
<h1><%= link_to "Create Project", new_project_path %></h1>
<br>
<p>------------------------------------------</p>
<% @projects.each do |project| %>
	<div>
		<h2><%= link_to project.name, project %></h2>
		<p><%= truncate(project.description, length:100) %></p>
		<p><%= time_ago_in_words(project.created_at) %></p>
	</div>
<% end %>
<p>------------------------------------------</p>

app/views/projects/new.html.erb
<%= form_for @project, url: {action: "create"} do |f| %>
  <%= label_tag "Name" %>
  <%= f.text_field :name %>
  </br></br></br>
  <%= label_tag "Description" %>
  <%= f.text_area :description, size: "60x12" %>
  </br></br></br>
  <%= f.submit "Create" %>
<% end %>

app/views/projects/show.html.erb
<h1>Name: <%= @project.name %></h1>
<h2>Description: <%= @project.description%></h2>

<p><%= link_to "Create User Story", new_project_user_story_path(@project) %></p>
<p><%= link_to "Modify project", edit_project_path %></p>
<p><%= link_to "Delete Project", project_path, method: :delete, data: { confirm: "Are you sure?" } %> </p>
<br>
<h3> USER STORIES </h3>
<br>
<p>------------------------------------------</p>
<% @project.user_stories.each_with_index do |story, index| %>
	<div>
		<h1> <%= index + 1 %>. User Story</h1>
		<p><%= link_to story.actor, project_user_story_path(@project, story) %></p>
    <p><%= story.goal %></p>
		<p><%= story.reason %></p>
		<p><%= story.criteria %></p>
		<p><%= story.priority %></p>

		<p><%= time_ago_in_words(story.created_at) %></p>
	</div>
	<%if story != @project.user_stories.last %>
		<p>------------------------------------------</p>
	<%end%>
<% end %>
<p>------------------------------------------</p>

app/views/user_stories/edit.html.erb
<h1>Edit User Story</h1>

<% if @user_story.errors.any? %> 
    <ul>
    <% @user_story.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>

<%= form_for @user_story, url: {action: "update"} do |f| %>
  <%= label_tag "Actor" %>
  <%= f.text_field :actor %>
  </br></br></br>
  <%= label_tag "Goal" %>
  <%= f.text_field :goal %>
  </br></br></br>
  <%= label_tag "Reason" %>
  <%= f.text_field :reason %>
  </br></br></br>
  <%= label_tag "Acceptance criteria" %>
  <%= f.text_area :criteria, size: "60x12" %>
  </br></br></br>
  <%= label_tag "Priority" %>
  <%= f.text_field :priority %>
  </br></br></br>  <%= f.submit "Update" %>
<% end %>
<p><%= link_to "Cancel", project_user_story_path(@project, @user_story) %></p>

app/views/user_stories/index.html.erb
<h1>User stories</h1>
<br>
<p><%= link_to "Create User Story", new_project_user_story_path(@project) %></p>
<br>
<p>------------------------------------------</p>
<% @user_stories.each do |story| %>
	<div>
		<h2><%= story.actor %></h2>
    <h2><%= story.goal %></h2>
		<h2><%= story.reason %></h2>
		<h2><%= story.criteria %></h2>
		<h2><%= story.priority %></h2>
		<p><%= time_ago_in_words(story.created_at) %></p>
	</div>
<% end %>
<p>------------------------------------------</p>

app/views/user_stories/new.html.erb
<%= form_for @user_story, url: {action: "create"} do |f| %>
  <%= label_tag "Actor" %>
  <%= f.text_field :actor %>
  </br></br></br>
  <%= label_tag "Goal" %>
  <%= f.text_field :goal %>
  </br></br></br>
  <%= label_tag "Reason" %>
  <%= f.text_field :reason %>
  </br></br></br>
  <%= label_tag "Acceptance criteria" %>
  <%= f.text_area :criteria, size: "60x12" %>
  </br></br></br>
  <%= label_tag "Priority" %>
  <%= f.text_field :priority %>
  </br></br></br>
  <%= f.submit "Create" %>
<% end %>

app/views/user_stories/show.html.erb
<p><%= @user_story.actor %></p>
<p><%= @user_story.goal %></p>
<p><%= @user_story.reason %></p>
<p><%= @user_story.criteria %></p>
<p><%= @user_story.priority %></p>

<br>
<br>

<p><%= link_to "Back to Project", @project%></p>
<p><%= link_to "Edit User Story", edit_project_user_story_path(@project, @user_story) %></p>
<p><%= link_to "Delete User Story", project_user_story_path, method: :delete, data: { confirm: "Are you sure?"} %> </p>
<p><%= link_to "Create new User Story", new_project_user_story_path(@project) %></p>

app/views/welcome/index.html.erb
<div class="container">
  <h3>Welcome</h3>
</div>